name       : bundler
version    : 1.13.0
release    : 2
source     :
    - https://rubygems.org/downloads/bundler-1.13.0.gem : 0c779c47e2561b8bab7c12f82d9ca5d3b0c0a6f7839bacaf1ddec1c2218db929
license    : MIT
component  : programming.tools
summary    : Manage your application's gem dependencies with less pain
description: |
    Manage your application's gem dependencies with less pain
extract    : no
builddeps  :
    - pkgconfig(ruby-2.2)
rundeps    :
    - git
    - ruby-devel
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/bundler-$version.gem
