name       : bundler
version    : 1.16.3
release    : 5
source     :
    - https://rubygems.org/downloads/bundler-1.16.3.gem : d89111fd6fcea3039df8f945a6be00988e29f32f9271ee35a14c7b83a36ced6a
license    : MIT
component  : programming.tools
summary    : Manage your application's gem dependencies with less pain
description: |
    Manage your application's gem dependencies with less pain
extract    : no
builddeps  :
    - pkgconfig(ruby-2.3)
rundeps    :
    - git
    - ruby-devel
install    : |
    export geminstalldir=$(ruby -e'puts Gem.default_dir')
    export GEM_HOME=$geminstalldir
    export GEM_PATH=$geminstalldir
    gem install \
        --ignore-dependencies \
        --no-user-install \
        -i "$installdir/$geminstalldir" \
        -n "$installdir/usr/bin" \
        $sources/bundler-$version.gem
